spring:
  application:
    name: spring-restaurant-api
  elasticsearch:
    uris: http://localhost:9200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/restaurant-review